// Generated by Haxe 4.2.1+bf9ff69
import { RPM } from "../path.js";
;(function ($global) { "use strict";
function Main_main() {
	console.log("src/Main.hx:7:",RPM.Common);
	console.log("src/Main.hx:8:","Paper Maker plugin from Haxe programming language");
}
class haxe_iterators_ArrayIterator {
	constructor(array) {
		this.current = 0;
		this.array = array;
	}
	hasNext() {
		return this.current < this.array.length;
	}
	next() {
		return this.array[this.current++];
	}
}
{
}
Main_main();
})({});
